providers:
  docker:
    exposedByDefault: false

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  leresolver:
    acme:
      email: supp@atservers.net
      storage: acme.json
      httpChallenge:
        entryPoint: web
